package betty-blocks:action@0.1.0;

interface action  {
   run: func() -> result<string, string>;
}

world app {
   import betty-blocks:create/create@0.1.0;
   import betty-blocks:update/update@0.1.0;

   export action;
}
